services:
  postgres:
    container_name: pyconau_tute_pg
    image: postgres:16.2-bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - ${PGPORT:-5432}:5432
    networks:
      - my-network
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d

networks:
  my-network:
    driver: bridge
